#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler"
Bundler.setup

require "renderer"

if ARGV.length != 2
  puts "Usage: docrb-html INPUT OUTPUT"
  exit 1
end

Renderer.configure(ARGV.shift, ARGV.shift).render
