# frozen_string_literal: true
module Docrb
  class Parser
    class Module < Container
      def kind: () -> :module

      def initialize: (Parser parser, Container? parent, untyped node) -> void

      def instance_method_added: (Parser parser, untyped node, Method method) -> void

      def handle_parsed_node: (Parser parser, untyped node) -> void
    end
  end
end
