#!/bin/bash

set -e

rb_args=()
while test $# -gt 0; do
  case "$1" in
    --root-path*)
      export NEXT_BASE_PATH=`echo $1 | sed -e 's/^[^=]*=//g'`;
      shift;
      ;;
    --gh-pages)
      export DOCRB_TO_GH_PAGES=true;
      shift;
      ;;
    *)
      rb_args+=($1)
      shift;
      ;;
  esac
done

echo "Compiling metadata..."
cd /docrb/docrb
bin/docrb /work ../docrb-react/.docrb $rb_args

echo "Compiling HTML..."
cd ../docrb-react
yarn build
yarn export

cp -r /docrb/docrb-react/out/* /output

if [ -n "$DOCRB_TO_GH_PAGES" ]; then
    touch /output/.nojekyll;
fi
