import {BaseFooter, Left, Right} from "@/styles/footer";
import {updatedAt, version} from "@/lib/index";
import {Link} from "@/components/link";

export const Footer = () => (
  <BaseFooter>
    <Left>
      Last Updated {updatedAt}
    </Left>
    <Right>
      Generated by <Link href="https://github.com/heyvito/docrb" text="Docrb" /> version {version}
    </Right>
  </BaseFooter>
)
