# frozen_string_literal: true

source "https://rubygems.org"

gem "docrb-html", path: "../docrb-html"

gem "docrb-parser", path: "../docrb-parser"

# Specify your gem's dependencies in docrb.gemspec
gemspec

group :development do
  gem "rake", "~> 13.0"

  gem "rspec", "~> 3.0"

  gem "rubocop", "~> 1.21"

  gem "byebug"

  gem "awesome_print"
end
