module Renderer
  module Entities
    class Attribute
      attr_accessor name: String

      attr_accessor source: untyped # TODO

      attr_accessor definition: AttributeDefinition

      attr_accessor overriding: untyped # TODO

      attr_accessor parent: Class

      def initialize: (Class parent, String name, Base::model model) -> void
    end
  end
end
