module Renderer
  module Entities
    class MethodArgument
      type argument_type = :arg | :optarg | :kwoptarg | :kwarg
      attr_accessor name: String

      attr_accessor parent: MethodDefinition

      attr_accessor type: argument_type

      attr_accessor value: untyped

      attr_accessor value_type: String

      def initialize: (MethodDefinition parent, Base::model arg) -> void

      def positional?: () -> bool

      def optional?: () -> bool

      def kwarg?: () -> bool
    end
  end
end
