module Renderer
  module Entities
    class MethodDefinition
      attr_accessor args: ::Array[MethodArgument]

      attr_accessor defined_by: SourceDefinition

      attr_accessor doc: untyped # TODO

      attr_accessor name: String

      attr_accessor overridden_by: untyped # TODO

      attr_accessor visibility: Base::visibility

      attr_accessor parent: Container

      def initialize: (Container parent, Base::model model) -> void

      def protected?: () -> bool

      def public?: () -> bool

      def private?: () -> bool
    end
  end
end
