module Renderer
  module Entities
    class Reference[T]
      type model = Base::model | String
      @parent: Container
      @name: String
      @class_path: ::Array[String]
      @field: Symbol
      @target: untyped
      @broken: bool

      def initialize: (Container parent, model model, Symbol field) -> void

      def resolved?: () -> bool

      def broken?: () -> bool
    end
  end
end
