name: Ruby

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/docrb
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run Rubocop
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/docrb
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run Rspec
      run: bundle exec rspec
